# Markdown linting configuration for markdownlint-cli2
# https://github.com/DavidAnson/markdownlint-cli2
# Globs to ignore
ignores:
  - "**/node_modules/**"
  - "**/target/**"
# Rules configuration
config:
  # Default: all rules enabled
  default: true
  # Common adjustments for technical documentation
  MD013: false # Line length - often too restrictive for technical docs
  MD024: false # Multiple headings with same content - common in technical docs with repeated sections
  MD031: false # Fenced code blocks should be surrounded by blank lines - not always applicable
  MD033: false # Inline HTML - sometimes needed for formatting
  MD040: false # Fenced code blocks should have a language specified - not always applicable
  MD041: false # First line in file should be top-level heading - not always applicable
