comment_width                = 120
condense_wildcard_suffixes   = true
doc_comment_code_block_width = 120
edition                      = "2024"
fn_params_layout             = "Tall"
format_code_in_doc_comments  = true
format_strings               = true
group_imports                = "StdExternalCrate"
imports_granularity          = "Crate"
max_width                    = 120
normalize_comments           = true
normalize_doc_attributes     = true
reorder_impl_items           = true
reorder_imports              = true
style_edition                = "2024"
wrap_comments                = true

ignore = ["db/entity/src/codegen", "ethereum/bindings/src/codegen"]
