---
name: Integration Test
on:
  workflow_call:
    inputs:
      image:
        description: Docker image to test
        required: true
        type: string
jobs:
  integration-test:
    name: Integration Tests
    runs-on: depot-ubuntu-22.04-4
    timeout-minutes: 20
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup Nix
        uses: hoprnet/hopr-workflows/actions/setup-nix@c8d45034bb33307dfda3b4dfcd1fc4000cadc05a # setup-nix-v1
        with:
          cachix_cache_name: blokli
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Setup GCP
        uses: hoprnet/hopr-workflows/actions/setup-gcp@12c56020e16036982e6cc529848edeedfc705865 # master
        with:
          google-credentials: ${{ secrets.GCP_SA_GITHUB_RUNNER }}
          login-artifact-registry: 'true'
          install-sdk: 'false'
      - name: Run Integration tests
        env:
          BLOKLI_TEST_REMOTE_IMAGE: ${{ inputs.image }}
        run: |-
          nix develop -c cargo test --package blokli-integration-tests
